###################################################################################################
# |                                        When Pickup                                          | #
# |                                   Author: Hexsook Smith                                     | #
###################################################################################################

# The radius within which items can be picked up
pickup-radius: 1